#!/usr/bin/env python3
"""Regenerate REGISTRY.md and the BACKEND_GUILD.md adoption matrix from
the frontmatter of every SKILL.md.
Usage:
    python3 skills/build-indexes.py             # rewrite files in place
    python3 skills/build-indexes.py --check     # exit 1 if files would change (CI)
"""
import os, re, sys, glob, json, argparse, hashlib
ROOT = os.path.dirname(os.path.abspath(__file__))
FM_RE = re.compile(r"^---\n(.*?)\n---\n", re.S)
def parse_fm(text):
    m = FM_RE.match(text)
    if not m:
        return {}
    fm = m.group(1)
    out = {}
    lines = fm.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        mm = re.match(r"^([a-zA-Z_]+):\s*(.*)$", line)
        if not mm:
            i += 1
            continue
        k, v = mm.group(1), mm.group(2).strip()
        # Handle YAML block scalars: ">" (folded) and "|" (literal)
        if v in ('>', '|'):
            parts = []
            i += 1
            while i < len(lines) and (lines[i].startswith('  ') or lines[i].startswith('\t')):
                parts.append(lines[i].strip())
                i += 1
            out[k] = ' '.join(parts) if v == '>' else '\n'.join(parts)
            continue
        if v.startswith("[") and v.endswith("]"):
            inner = v[1:-1].strip()
            out[k] = [x.strip() for x in inner.split(",") if x.strip()] if inner else []
        elif v in ("true", "false"):
            out[k] = (v == "true")
        else:
            out[k] = v
        i += 1
    return out
def collect():
    skills = []
    for p in sorted(glob.glob(os.path.join(ROOT, "*", "SKILL.md"))):
        folder = os.path.basename(os.path.dirname(p))
        fm = parse_fm(open(p, encoding="utf-8").read())
        fm["_folder"] = folder
        skills.append(fm)
    return skills
def render_registry(skills):
    out  = ["# Skills Registry\n"]
    out += ["<!-- AUTO-GENERATED by build-indexes.py — DO NOT EDIT BY HAND. -->",
            "<!-- Re-run: python3 build-indexes.py -->\n",
            "Machine-readable index of every skill in this catalogue.",
            "Used by agents to pick a skill and by `validate-skills.sh` to",
            "enforce that every skill has a home in this file.\n",
            "## Totals\n",
            f"| Tier | Count |", f"| --- | --- |",
            f"| Public | **{len(skills)}** |\n",
            "## Public skills\n",
            "Legend — **T** = ships templates; **HITL** = human-in-the-loop;",
            "**Tier** = MUST / SHOULD / MAY adoption tier.\n",
            "| Skill | Tier | T | HITL | Applies to | Depends on | One-line summary |",
            "| --- | :-: | :-: | :-: | --- | --- | --- |"]
    for s in skills:
        f = s["_folder"]
        tier = s.get("tier","?").upper()
        t   = "✓" if s.get("ships_templates") else ""
        h   = "✓" if s.get("hitl") else ""
        apps = ", ".join(s.get("applies_to",[])) or "—"
        deps = ", ".join(f"`{d}`" for d in s.get("depends_on",[])) or "—"
        desc = s.get("description","").split(".")[0].strip()[:140]
        out.append(f"| [`{f}`](./{f}/SKILL.md) | {tier} | {t} | {h} | {apps} | {deps} | {desc}. |")
    out.append("")
    return "\n".join(out) + "\n"
def render_matrix(skills):
    """Render the MUST/SHOULD/MAY adoption matrix snippet for BACKEND_GUILD.md."""
    by_tier = {"must":[], "should":[], "may":[]}
    for s in skills:
        by_tier.setdefault(s.get("tier","may"), []).append(s)
    lines = []
    titles = {"must":"MUST — every service",
              "should":"SHOULD — when the service has the feature",
              "may":"MAY — useful but optional"}
    for tier in ("must","should","may"):
        bucket = by_tier[tier]
        lines.append(f"### {titles[tier]} ({len(bucket)})\n")
        lines.append("| Skill | One-line summary |")
        lines.append("| --- | --- |")
        for s in bucket:
            f = s["_folder"]
            desc = s.get("description","").split(".")[0].strip()[:160]
            lines.append(f"| [`{f}`](./{f}/SKILL.md) | {desc}. |")
        lines.append("")
    return "\n".join(lines)
def render_dep_graph(skills):
    """Mermaid graph of inter-skill dependencies, snippet for BACKEND_GUILD.md."""
    lines = ["```mermaid", "graph LR"]
    for s in skills:
        f = s["_folder"]
        for d in s.get("depends_on", []):
            lines.append(f"  {d.replace('-','_')} --> {f.replace('-','_')}")
    lines.append("```")
    return "\n".join(lines)
def splice(path, marker, payload):
    """Replace the region between <!-- BEGIN AUTO:<marker> --> and <!-- END AUTO:<marker> -->."""
    body = open(path, encoding="utf-8").read()
    begin = f"<!-- BEGIN AUTO:{marker} -->"
    end   = f"<!-- END AUTO:{marker} -->"
    pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    block = f"{begin}\n{payload}\n{end}"
    if pat.search(body):
        new = pat.sub(block, body)
    else:
        new = body.rstrip() + "\n\n" + block + "\n"
    return new
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="Exit non-zero if any file would change.")
    args = ap.parse_args()
    skills = collect()
    targets = {
        os.path.join(ROOT, "REGISTRY.md"): render_registry(skills),
    }
    # Splice into BACKEND_GUILD.md
    bg = os.path.join(ROOT, "BACKEND_GUILD.md")
    if os.path.exists(bg):
        new_bg = splice(bg, "matrix", render_matrix(skills))
        new_bg = splice_text(new_bg, "graph", render_dep_graph(skills))
        targets[bg] = new_bg
    changed = []
    for path, content in targets.items():
        existing = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if existing != content:
            changed.append(os.path.relpath(path))
            if not args.check:
                open(path, "w", encoding="utf-8").write(content)
    if args.check:
        if changed:
            print("Generated docs are out of date:", *changed, sep="\n  ")
            print("\nRun: python3 build-indexes.py")
            sys.exit(1)
        print("Generated docs are up to date.")
    else:
        if changed:
            print("Regenerated:", *changed, sep="\n  ")
        else:
            print("No changes — already up to date.")
def splice_text(body, marker, payload):
    """Same as splice() but operates on a string (not a file path)."""
    begin = f"<!-- BEGIN AUTO:{marker} -->"
    end   = f"<!-- END AUTO:{marker} -->"
    pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    block = f"{begin}\n{payload}\n{end}"
    if pat.search(body):
        return pat.sub(block, body)
    return body.rstrip() + "\n\n" + block + "\n"
if __name__ == "__main__":
    main()
